export const array = [
  {
    width: "40px",
    height: "40px",
    leftTopText: "~",
    textEn: "`",
    textRu:"`",
    backgroundColor: "#696969",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "!",
    textEn: "1",
    textRu:"1",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "@",
    textEn: "2",
    textRu:"2",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "#",
    textEn: "3",
    textRu:"3",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "$",
    textEn: "4",
    textRu:"4",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "%",
    textEn: "5",
    textRu:"5",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: ":",
    textEn: "6",
    textRu:"6",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "?",
    textEn: "7",
    textRu:"7",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "*",
    textEn: "8",
    textRu:"8",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "(",
    textEn: "9",
    textRu:"9",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: ")",
    textEn: "0",
    textRu:"0",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "-",
    textEn: "-",
    textRu:"-",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "+",
    textEn: "=",
    textRu:"=",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "115px",
    height: "40px",
    leftTopText: "",
    textEn: "Backspace",
    textRu:"Backspace",
    backgroundColor: "#696969",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "50px",
    height: "40px",
    leftTopText: "",
    textEn: "Tab",
    textRu:"Tab",
    backgroundColor: "#696969",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "Q",
    textRu: "Й", 
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "W",
    textRu: "Ц", 
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "E", 
    textRu: "У",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "R", 
    textRu: "К",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "T", 
    textRu: "Е",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "Y", 
    textRu: "Н",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "U", 
    textRu: "Г",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "I", 
    textRu: "Ш",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "O", 
    textRu: "Щ",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "P", 
    textRu: "З",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "[", 
    textRu: "Х",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "]", 
    textRu: "Ъ",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "/",
    textEn: "\\", 
    textRu: "\\",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "50px",
    height: "40px",
    leftTopText: "",
    textEn: "DEL",
    textRu: "DEL",
    backgroundColor: "#696969",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "115px",
    height: "40px",
    leftTopText: "",
    textEn: "Caps Lock",
    textRu: "Caps Lock",
    backgroundColor: "#696969",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "A", 
    textRu: "Ф",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "S", 
    textRu: "Ы",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "D", 
    textRu: "В",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "F", 
    textRu: "А",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "G", 
    textRu: "П",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "H", 
    textRu: "Р",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "J", 
    textRu: "О",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "K", 
    textRu: "Л",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "L", 
    textRu: "Д",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: ";", 
    textRu: "Ж",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "\"", 
    textRu: "Э",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "100px",
    height: "40px",
    leftTopText: "",
    textEn: "ENTER",
    textRu: "ENTER",
    backgroundColor: "#696969",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "115px",
    height: "40px",
    leftTopText: "",
    textEn: "Shift",
    textRu: "Shift",
    backgroundColor: "#696969",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "\"",
    textRu: "\"",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },

  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "Z", 
    textRu: "Я",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "X", 
    textRu: "Ч",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "C", 
    textRu: "C",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "V", 
    textRu: "М",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "B", 
    textRu: "И",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "N", 
    textRu: "Т",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "M", 
    textRu: "Ь",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: ",", 
    textRu: "Б",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: ".", 
    textRu: "Ю",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "/",
    textRu: "/",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "▲",
    textRu: "▲",
    backgroundColor: "#696969",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "45px",
    height: "40px",
    leftTopText: "",
    textEn: "Shift",
    textRu: "Shift",
    backgroundColor: "#696969",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "60px",
    height: "40px",
    leftTopText: "",
    textEn: "Ctrl",
    textRu: "Ctrl",
    backgroundColor: "#696969",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "15px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "Win",
    textRu: "Win",
    backgroundColor: "#696969",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "15px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "Alt",
    textRu: "Alt",
    backgroundColor: "#696969",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "15px",
  },
  {
    width: "350px",
    height: "40px",
    leftTopText: "",
    textEn: " ",
    textRu: " ",
    backgroundColor: "#C0C0C0",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "15px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "Alt",
    textRu: "Alt",
    backgroundColor: "#696969",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "60px",
    height: "40px",
    leftTopText: "",
    textEn: "Ctrl",
    textRu: "Ctrl",
    backgroundColor: "#696969",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "◄",
    textRu: "◄",
    backgroundColor: "#696969",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "40px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "▼",
    textRu: "▼",
    backgroundColor: "#696969",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "20px",
  },
  {
    width: "40px",
    height: "40px",
    leftTopText: "",
    textEn: "►",
    textRu: "►",
    backgroundColor: "#696969",
    color: "#fff",
    padding: "5px",
    borderRadius: "10px",
    fontSize: "40px",
  },
];

// #696969 - darkGray
// #C0C0C0 - lightGray
// #fff - white
